import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* 整体页面容器 */}
          <div className="min-h-screen flex flex-col bg-background text-foreground">
            <Navbar />
            {/* 内容区域：居中并控制最大宽度 */}
            <main className="flex-1 flex justify-center items-start px-4 py-8">
              <div className="w-full max-w-4xl">{children}</div>
            </main>
          </div>
        </AuthProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
